export enum FieldName {
	FIRST_NAME = "first-name",
	LAST_NAME = "last-name",
	PHONE = "phone",
	EMAIL = "email",
	PASSWORD = "password",
	TEXT = "text",
	FILE = "file",
	FILES = "files",
	POLICY = "policy",
	CHECKBOX_GROUP = "checkbox-group",
	CHECKBOX_GROUP_2 = "checkbox-group2",
	RADIO = "radio",
	SELECT = "select",
	MULTI_SELECT = "multi-select",
}
