declare namespace NodeJS {
	interface ProcessEnv {
		NEXT_PUBLIC_BUILD_PROFILE: string;
		NEXT_PUBLIC_SITE_URL: string;
		NEXT_PUBLIC_STORAGE_PATHNAME: string;
		NEXT_PUBLIC_STORAGE_URL: string;
		NEXT_PUBLIC_API_URL: string;
		NEXT_PUBLIC_YANDEX_METRIKA_ENABLED: string;
		NEXT_PUBLIC_YANDEX_METRIKA_KEY: string;
		NEXT_PUBLIC_GOOGLE_ANALYTICS_ENABLED: string;
		NEXT_PUBLIC_GOOGLE_ANALYTICS_KEY: string;
		NEXT_PUBLIC_BASIC_AUTH_LOGIN: string;
		NEXT_PUBLIC_BASIC_AUTH_PASSWORD: string;
	}
}
